server:
  port: 8085
  servlet:
    context-path: /api/rearinfo

spring:
  profiles:
    active: dev
  datasource:
    name: muxui_blog
    url: jdbc:mysql://127.0.0.1:3306/muxui_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: muxui_blog
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB  #设置支持的单个上传文件大小
      max-request-size: 6MB  #设置最大的请求文件大小，设置总体大小的请求
      file-size-threshold: 512KB #当上传文件达到指定配置量的时候，会将文件内容写入到磁盘
      location: /   #设置上传文件的临时目录
  redis:
    host: 127.0.0.1
    port: 6379
    password: Ia3dfsfgw23

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: com.muxui.blog.service.*.dao
  global-config:
    db-config:
      #数据库大写下划线转换
      capital-mode: false
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-configuration-to-camel-case: true
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:config/spring-logback.xml

github:
  client:
    id:
    secret:
    url: http://127.0.0.1:8085/api/rearinfo/auth/github/callback